#include "decoder.h"
#include "rm_terminal.pb.h"
#include <cmath>

namespace rm_terminal {
template<class T> static bool finite(const T& value) { return std::isfinite(value); }
bool Decoder::accept(const std::string& topic, const std::string& bytes, MonotonicMs now) {
    if (topic == "GameStatus") { rm::GameStatus x; if (!x.ParseFromString(bytes)) return false; inbound::GameStatus p; if(x.has_current_round())p.current_round=x.current_round();if(x.has_total_rounds())p.total_rounds=x.total_rounds();if(x.has_red_score())p.red_score=x.red_score();if(x.has_blue_score())p.blue_score=x.blue_score();if(x.has_current_stage())p.current_stage=x.current_stage();if(x.has_stage_countdown_sec())p.stage_countdown_sec=x.stage_countdown_sec();if(x.has_stage_elapsed_sec())p.stage_elapsed_sec=x.stage_elapsed_sec();if(x.has_is_paused())p.is_paused=x.is_paused();if(x.has_winner())p.winner=x.winner();if(x.has_end_reason())p.end_reason=x.end_reason();if(x.has_red_base_hp())p.red_base_hp=x.red_base_hp();if(x.has_red_base_max_hp())p.red_base_max_hp=x.red_base_max_hp();if(x.has_blue_base_hp())p.blue_base_hp=x.blue_base_hp();if(x.has_blue_base_max_hp())p.blue_base_max_hp=x.blue_base_max_hp();if(x.has_red_outpost_hp())p.red_outpost_hp=x.red_outpost_hp();if(x.has_red_outpost_max_hp())p.red_outpost_max_hp=x.red_outpost_max_hp();if(x.has_blue_outpost_hp())p.blue_outpost_hp=x.blue_outpost_hp();if(x.has_blue_outpost_max_hp())p.blue_outpost_max_hp=x.blue_outpost_max_hp();if(x.has_red_team_name())p.red_team_name=x.red_team_name();if(x.has_blue_team_name())p.blue_team_name=x.blue_team_name();if(x.has_red_economy())p.red_economy=x.red_economy();if(x.has_blue_economy())p.blue_economy=x.blue_economy();if(x.has_red_total_damage())p.red_total_damage=x.red_total_damage();if(x.has_blue_total_damage())p.blue_total_damage=x.blue_total_damage();if(x.has_red_fortress_sec())p.red_fortress_sec=x.red_fortress_sec();if(x.has_blue_fortress_sec())p.blue_fortress_sec=x.blue_fortress_sec();if(x.has_fortress_holder())p.fortress_holder=x.fortress_holder();if(x.has_red_kills())p.red_kills=x.red_kills();if(x.has_blue_kills())p.blue_kills=x.blue_kills();if(x.has_red_energy_activations())p.red_energy_activations=x.red_energy_activations();if(x.has_blue_energy_activations())p.blue_energy_activations=x.blue_energy_activations(); return store_.apply(p,now); }
    if (topic == "Event") { rm::Event x; if (!x.ParseFromString(bytes)) return false; if(x.has_timestamp_ms() && last_event_timestamp_ && x.timestamp_ms() <= *last_event_timestamp_) return false; inbound::Event p; if(x.has_timestamp_ms())p.timestamp_ms=x.timestamp_ms(); if(x.has_level())p.level=x.level(); if(x.has_text())p.text=x.text(); if(x.has_faction())p.faction=x.faction(); const bool accepted=store_.apply(p,now); if(accepted && x.has_timestamp_ms())last_event_timestamp_=x.timestamp_ms(); return accepted; }
    if (topic == "RobotDynamicStatus") { rm::RobotDynamicStatus x; if(!x.ParseFromString(bytes)||!x.has_robot_id()||x.robot_id()!=source_.value)return false; inbound::RobotDynamicStatus p; p.robot_id=x.robot_id(); if(x.has_current_hp())p.current_hp=x.current_hp();if(x.has_max_hp())p.max_hp=x.max_hp();if(x.has_shooter_heat_17mm())p.shooter_heat_17mm=x.shooter_heat_17mm();if(x.has_shooter_heat_limit())p.shooter_heat_limit=x.shooter_heat_limit();if(x.has_bullet_speed()){if(!finite(x.bullet_speed()))return false;p.bullet_speed=x.bullet_speed();}if(x.has_remaining_ammo())p.remaining_ammo=x.remaining_ammo();if(x.has_coin())p.coin=x.coin();if(x.has_chassis_power())p.chassis_power=x.chassis_power();if(x.has_buffer_energy())p.buffer_energy=x.buffer_energy(); return store_.apply(p,source_,now); }
    if (topic == "RobotModuleStatus") { rm::RobotModuleStatus x; if(!x.ParseFromString(bytes))return false; inbound::RobotModuleStatus p; if(x.has_power_manager())p.power_manager=x.power_manager();if(x.has_rfid())p.rfid=x.rfid();if(x.has_light_strip())p.light_strip=x.light_strip();if(x.has_small_shooter())p.small_shooter=x.small_shooter();if(x.has_big_shooter())p.big_shooter=x.big_shooter();if(x.has_uwb())p.uwb=x.uwb();if(x.has_armor())p.armor=x.armor();if(x.has_video_transmission())p.video_transmission=x.video_transmission();if(x.has_capacitor())p.capacitor=x.capacitor();if(x.has_main_controller())p.main_controller=x.main_controller();if(x.has_laser_detection_module())p.laser_detection_module=x.laser_detection_module(); return store_.apply(p,source_,now); }
    if (topic == "RobotPosition") { rm::RobotPosition x; if(!x.ParseFromString(bytes))return false; inbound::RobotPosition p; if(x.has_x())p.x=x.x(); if(x.has_y())p.y=x.y(); if(x.has_yaw())p.yaw=x.yaw(); return store_.apply(p,source_,now); }
    if (topic == "RobotTelemetry") { rm::RobotTelemetry x; if(!x.ParseFromString(bytes))return false; inbound::RobotTelemetry p; if(x.has_sequence())p.sequence=x.sequence();if(x.has_timestamp_us())p.timestamp_us=x.timestamp_us();if(x.has_gimbal_yaw()){if(!finite(x.gimbal_yaw()))return false;p.gimbal_yaw=x.gimbal_yaw();}if(x.has_gimbal_pitch())p.gimbal_pitch=x.gimbal_pitch();if(x.has_chassis_mode())p.chassis_mode=x.chassis_mode();if(x.has_vision_online())p.vision_online=x.vision_online();if(x.has_autoaim_enabled())p.autoaim_enabled=x.autoaim_enabled();if(x.has_target_locked())p.target_locked=x.target_locked();if(x.has_target_id())p.target_id=x.target_id();if(x.has_bbox_cx())p.bbox_cx=x.bbox_cx();if(x.has_bbox_cy())p.bbox_cy=x.bbox_cy();if(x.has_bbox_w())p.bbox_w=x.bbox_w();if(x.has_bbox_h())p.bbox_h=x.bbox_h(); return store_.apply(p,source_,now); }
    if (topic == "BlindStatus") { rm::BlindStatus x; if(!x.ParseFromString(bytes))return false; inbound::BlindStatus p; if(x.has_self_base_blinded())p.self_base_blinded=x.self_base_blinded(); if(x.has_blind_started_ms())p.blind_started_ms=x.blind_started_ms(); if(x.has_blind_remaining_ms())p.blind_remaining_ms=x.blind_remaining_ms(); if(x.has_cause())p.cause=x.cause(); return store_.apply(p,now); }
    if (topic == "RobotHealthSet") { rm::RobotHealthSet x; if(!x.ParseFromString(bytes))return false; inbound::RobotHealthSet p; p.entries.reserve(static_cast<std::size_t>(x.entries_size())); for(const auto& e : x.entries()){ inbound::RobotHealthEntry entry; if(e.has_robot_id())entry.robot_id=e.robot_id(); if(e.has_faction())entry.faction=e.faction(); if(e.has_current_hp())entry.current_hp=e.current_hp(); if(e.has_max_hp())entry.max_hp=e.max_hp(); p.entries.push_back(std::move(entry)); } return store_.apply(p,now); }
    if (topic == "RobotPositionSet") { rm::RobotPositionSet x; if(!x.ParseFromString(bytes))return false; inbound::RobotPositionSet p; p.entries.reserve(static_cast<std::size_t>(x.entries_size())); for(const auto& e : x.entries()){ inbound::RobotPositionEntry entry; if(e.has_robot_id())entry.robot_id=e.robot_id(); if(e.has_faction())entry.faction=e.faction(); if(e.has_is_self())entry.is_self=e.is_self(); if(e.has_x()){if(!finite(e.x()))return false;entry.x=e.x();} if(e.has_y()){if(!finite(e.y()))return false;entry.y=e.y();} if(e.has_yaw()){if(!finite(e.yaw()))return false;entry.yaw=e.yaw();} p.entries.push_back(std::move(entry)); } return store_.apply(p,now); }
    return false;
}
}
